#!/usr/bin/env ruby
# vim: filetype=ruby

# list-all-companies
#   List all the companies belonging to the organization identified by:
#     ARGV[0] || ENV['REACTOR_TEST_COMPANY'] || ENV['REACTOR_COMPANY_ID']

require_relative 'pinhole.rb'

ORG_ID = ARGV.first || ENV['REACTOR_ORG_ID'] || ENV['REACTOR_TEST_ORG_ID']
$Verbose = ENV['PINHOLE_VERBOSITY'] =~ /^\d+$/ ? $&.to_i :  2

def main
  raise 'Define ARGV[0], REACTOR_ORG_ID, or REACTOR_TEST_ORG_ID' unless
    ORG_ID && ORG_ID != ''
  raise "Invalid Org ID: #{ORG_ID.inspect}" unless
    ORG_ID =~ /^[0-9a-f]{24}@adobeorg$/i
  blacksmith = Blacksmith.new
  puts "Server: #{blacksmith}" if $Verbose >= 1
  org = Org.find(blacksmith, id: ORG_ID)
  org.company('ALL')
  puts "---"
  puts "Find all Companies (not constrained by org)"
  Company.all(blacksmith) # not constrained by org
rescue GenericError => error
  puts "Exception:\n  #{error.to_s}"
end

main
