#!/usr/bin/env ruby
# vim: filetype=ruby

# find-any-company:
#   Find any company in my org

require_relative '../pinhole.rb'

ORG_ID = ENV['REACTOR_ORG_ID']
$Verbose = ENV['PINHOLE_VERBOSITY'] =~ /^\d+$/ ? $&.to_i :  2

def main
  blacksmith = Blacksmith.new
  puts "Server: #{blacksmith}" if $Verbose >= 1
  org = Org.find(blacksmith, id: ORG_ID)
  org.company('ANY')
rescue GenericError => error
  puts "Exception:\n  #{error.to_s}"
end

main
