#!/usr/bin/env ruby
# vim: filetype=ruby

# find-the-extension-package
#   Find the extension package whose id is
#     ARGV[0] || ENV['REACTOR_TEST_EXTENSION_PACKAGE_ID'] || ENV['REACTOR_EXTENSION_PACKAGE_ID']

require_relative '../pinhole.rb'

PACKAGE_ID = ARGV.first ||
  ENV['REACTOR_TEST_EXTENSION_PACKAGE_ID'] ||
  ENV['REACTOR_EXTENSION_PACKAGE_ID']
$Verbose = ENV['PINHOLE_VERBOSITY'] =~ /^\d+$/ ? $&.to_i :  2

def main
  raise 'Define ARGV[0], REACTOR_TEST_EXTENSION_PACKAGE_ID, or REACTOR_EXTENSION_PACKAGE_ID' unless
    PACKAGE_ID && PACKAGE_ID != ''
  raise "Invalid Extension Package ID: #{PACKAGE_ID.inspect}" unless
    PACKAGE_ID =~ /^EP[0-9a-f]{32}$/i
  blacksmith = Blacksmith.new
  puts "Server: #{blacksmith}" if $Verbose >= 1
  ExtensionPackage.find(blacksmith, id: PACKAGE_ID)
rescue GenericError => error
  puts "Exception:\n  #{error.to_s}"
end

main
