#!/usr/bin/env ruby
# vim: filetype=ruby

# kill-the-property PRa8139fa0d10547c8a6f64912fe6afed4
#   Delete the identified Property.

require_relative '../pinhole.rb'

ORG_ID = ENV['REACTOR_ORG_ID']
$Verbose = ENV['PINHOLE_VERBOSITY'] =~ /^\d+$/ ? $&.to_i :  2

def main
  blacksmith = Blacksmith.new
  puts "Server: #{blacksmith}" if $Verbose >= 1
  if ARGV.size != 1
    puts "usage: #{$0} PROPERTY_ID"
  elsif ARGV[0] !~ /^PR[0-9a-fA-F]{32}$/
    puts "Argument is not a PROPERTY ID: #{ARGV[0]}"
    exit 1
  else
    property = Property.new(blacksmith, ARGV[0])
    property.delete
  end
rescue GenericError => error
  puts "Exception:\n  #{error.to_s}"
end

main
