#!/usr/bin/env ruby
# vim: filetype=ruby

# kill-all-properties:
#   Find any Company in my Org and delete all its Properties.

require_relative '../pinhole.rb'

ORG_ID = ENV['REACTOR_ORG_ID']
$Verbose = ENV['PINHOLE_VERBOSITY'] =~ /^\d+$/ ? $&.to_i :  2

def main
  blacksmith = Blacksmith.new
  puts "Server: #{blacksmith}" if $Verbose >= 1
  org = Org.find(blacksmith, id: ORG_ID)
  company = org.company('ANY')
  company.property('ALL').each { |p| p.delete }
rescue GenericError => error
  puts "Exception (#{error.class}):\n  #{error.to_s}"
end

main
