#!/usr/bin/env ruby
# vim: filetype=ruby

# list-all-adapters
#   Find all the Adapters on any Property on any Company in my Org.
#
# list-all-adapters PRa8139fa0d10547c8a6f64912fe6afed4
#   Find all the Adapters on the named Property.

require_relative '../pinhole.rb'

ORG_ID = ENV['REACTOR_ORG_ID']
$Verbose = ENV['PINHOLE_VERBOSITY'] =~ /^\d+$/ ? $&.to_i :  2

def main
  blacksmith = Blacksmith.new
  puts "Server: #{blacksmith}" if $Verbose >= 1
  if ARGV.size > 1
    puts "usage: #{$0} [PROPERTY_ID]"
  elsif ARGV.size == 1 && ARGV[0] !~ /^PR[0-9a-fA-F]{32}$/
    puts "Argument is not a Property ID: #{ARGV[0]}"
    exit 1
  elsif ARGV.size > 0
    property = Property.find(blacksmith, id: ARGV[0])
    property.adapter('ALL')
  else
    org = Org.find(blacksmith, id: ORG_ID)
    property = org.company('ANY').property('ANY')
    adapter = property.adapter('ALL')
  end
rescue GenericError => error
  puts "Exception:\n  #{error.to_s}"
end

main
