#!/usr/bin/env ruby
# vim: filetype=ruby

# list-all-callbacks
#   List all the Callbacks on all Properties on any Company in my Org.
#
# list-all-callbacks PRa8139fa0d10547c8a6f64912fe6afed4
#   List all the Callbacks on the named Property.

=begin comment
To do the same in a Rails console:

  rl blacksmith  # connect to the blacksmith docker container
  source /srv/share/thom-credentials  # get REACTOR_COMPANY_ID defined
  RAILS_LOG_LEVEL=info rails console  # start up rails console, suppressing heartbeat messages
  Company.find(ENV['REACTOR_COMPANY_ID']).properties.map do |pr|
    puts "#{pr.id} #{pr.name}"
    pr.callbacks.each { |cb| puts "  #{cb.id} #{cb.url} #{cb.subscriptions}" }
  end

=end

require_relative '../pinhole.rb'

ORG_ID = ENV['REACTOR_ORG_ID']
$Verbose = ENV['PINHOLE_VERBOSITY'] =~ /^\d+$/ ? $&.to_i :  2

def main
  blacksmith = Blacksmith.new
  puts "Server: #{blacksmith}" if $Verbose >= 1
  if ARGV.size > 1
    puts "usage: #{$0} [PROPERTY_ID]"
    exit 1
  elsif ARGV.size == 1 && ARGV[0] !~ /^PR[0-9a-fA-F]{32}$/
    puts "Argument is not a Property ID: #{ARGV[0]}"
    exit 2
  elsif ARGV.size > 0
    properties = [Property.find(blacksmith, id: ARGV[0])]
  else
    org = Org.find(blacksmith, id: ORG_ID)
    properties = org.company('ANY').property('ALL')
  end

  properties.each do |property|
    puts "Callbacks for #{property.id}:"
    callbacks = property.callback('ALL')
  end

  # Instead: Find all the Callbacks on ANY Property on any Company in my Org.
  #property = org.company('ANY').property('ANY')
  #callbacks = property.callback('ALL')
rescue GenericError => error
  puts "Exception:\n  #{error.to_s}"
end

main
