#!/usr/bin/env ruby
# vim: filetype=ruby

# list-all-rules
#   List all the Users.

require_relative '../pinhole.rb'

ORG_ID = ENV['REACTOR_ORG_ID']
$Verbose = ENV['PINHOLE_VERBOSITY'] =~ /^\d+$/ ? $&.to_i :  2

def main
  blacksmith = Blacksmith.new
  puts "Server: #{blacksmith}" if $Verbose >= 1
  if ARGV.size > 0
    puts "usage: #{$0}"
    exit 1
  end
  org = Org.find(blacksmith, id: ORG_ID)
  users = org.user('ANY')
rescue GenericError => error
  puts "Exception:\n  #{error.to_s}"
end

main
