#!/usr/bin/env ruby
# vim: filetype=ruby
#
echo "NOT YET IMPLEMENTED"
echo "pending creation of make-new-extension"
exit 1
# make-new-rule-component
#   Find any Company in my Org.
#   Find or fake one Property on the Company.
#   Find or fake one Extension on the Property.
#   ...

require_relative '../pinhole.rb'

ORG_ID = ENV['REACTOR_ORG_ID']
$Verbose = ENV['PINHOLE_VERBOSITY'] =~ /^\d+$/ ? $&.to_i :  2

def main
  blacksmith = Blacksmith.new
  puts "Server: #{blacksmith}" if $Verbose >= 1
  if ARGV.size > 1
    puts "usage: #{$0} [PROPERTY_ID]"
  elsif ARGV.size == 1 && ARGV[0] !~ /^PR[0-9a-fA-F]{32}$/
    puts "Argument is not a Property ID: #{ARGV[0]}"
    exit 1
  elsif ARGV.size > 0
    property = Property.find(blacksmith, id: ARGV[0])
    property.adapter('NEW')
  else
    org = Org.find(blacksmith, id: ORG_ID)
    property = org.company('ANY').property('ONE')
    adapter = property.adapter('NEW')
  end
rescue GenericError => error
  puts "Exception:\n  #{error.to_s}"
end

main
