#!/usr/bin/env ruby
# vim: filetype=ruby

# make-new-extension-package
#   Make a new ExtensionPackage, using `./pinhole-test-EP.zip`.

require_relative '../pinhole.rb'

ORG_ID = ENV['REACTOR_ORG_ID']
$Verbose = ENV['PINHOLE_VERBOSITY'] =~ /^\d+$/ ? $&.to_i :  2
$ZipFile = "#{File.dirname(__FILE__)}/pinhole-test-EP.zip"

def main
  begin
    blacksmith = Blacksmith.new
    puts "Server: #{blacksmith}" if $Verbose >= 1
    org = Org.find(blacksmith, id: ORG_ID)
    org.make_extension_package(zipfilename: $ZipFile)
  rescue StandardError => error
    puts "Exception:\n  #{error.to_s}"
  end
end

main
